"""
single_voxel_test.py – Visualise a single voxel generated by the C++ engine.

Usage
-----
    python python/single_voxel_test.py [--biome NAME] [--headless] [--frames N]

Controls (interactive window)
------------------------------
    W/S       – zoom in / out
    A/D       – orbit left / right
    Q/E       – orbit up / down
    Escape    – quit
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure python/ directory is on the path for local imports.
_here = Path(__file__).parent.resolve()
sys.path.insert(0, str(_here))

# ── Import C++ engine ──────────────────────────────────────────────────────────
try:
    import voxel_core as ve
except ImportError:
    sys.exit(
        "ERROR: Cannot import 'voxel_core'. "
        "Build it first:\n  python setup.py build_ext --inplace"
    )

from camera import Camera
from renderer import VoxelRenderer, _HAS_OPENGL

try:
    import pygame
    _HAS_PYGAME = True
except ImportError:
    _HAS_PYGAME = False

# ── Biome name → BiomeType mapping ────────────────────────────────────────────
BIOME_MAP = {
    "air":      ve.BiomeType.Air,
    "ocean":    ve.BiomeType.Ocean,
    "beach":    ve.BiomeType.Beach,
    "plains":   ve.BiomeType.Plains,
    "forest":   ve.BiomeType.Forest,
    "desert":   ve.BiomeType.Desert,
    "tundra":   ve.BiomeType.Tundra,
    "mountain": ve.BiomeType.Mountain,
    "snow":     ve.BiomeType.Snow,
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Visualise a single voxel generated by the C++ engine."
    )
    p.add_argument(
        "--biome",
        default="plains",
        choices=list(BIOME_MAP.keys()),
        help="Biome type for the voxel (default: plains)",
    )
    p.add_argument(
        "--headless",
        action="store_true",
        help="Run without a window (for testing/CI)",
    )
    p.add_argument(
        "--frames",
        type=int,
        default=0,
        help="Run for N frames then exit (0 = unlimited, interactive only)",
    )
    return p.parse_args()


# ── Single voxel generation (C++ engine) ──────────────────────────────────────

def make_single_voxel_chunk(biome: ve.BiomeType) -> ve.Chunk:
    """Create a Chunk with a single solid voxel at position (0, 0, 0)."""
    chunk = ve.Chunk()
    chunk.set(0, 0, 0, ve.Voxel(True, biome))
    return chunk


def print_voxel_info(chunk: ve.Chunk, biome_name: str) -> None:
    """Print information about the single voxel and its generated mesh."""
    voxel = chunk.get(0, 0, 0)
    mesh  = chunk.build_mesh()
    vertex_count = len(mesh) // 7  # 7 floats per vertex: x,y,z,nx,ny,nz,biome_id

    print("─" * 50)
    print("Single Voxel — C++ Engine Test")
    print("─" * 50)
    print(f"  Voxel         : {voxel}")
    print(f"  Biome         : {biome_name}")
    print(f"  Solid         : {voxel.solid}")
    print(f"  Solid count   : {chunk.solid_count()}")
    print(f"  Mesh vertices : {vertex_count}")
    print(f"  Mesh floats   : {len(mesh)}")
    if mesh:
        # x, y, z, nx, ny, nz, biome_id
        print(
            "  First vertex  : x={:.2f} y={:.2f} z={:.2f} "
            "nx={:.2f} ny={:.2f} nz={:.2f} biome={:.0f}".format(*mesh[:7])
        )
    print("─" * 50)


# ── Interactive visualisation ──────────────────────────────────────────────────

def run_interactive(mesh: list, biome_name: str, max_frames: int) -> None:
    """Open an OpenGL window and display the single-voxel mesh."""
    if not _HAS_PYGAME:
        print("pygame not installed – cannot run interactive visualisation.")
        return

    renderer = VoxelRenderer(
        width=800, height=600,
        title=f"Single Voxel — {biome_name.capitalize()}",
    )

    # Upload the single-voxel mesh at chunk coord (0, 0, 0).
    renderer.upload_chunk_mesh(0, 0, 0, mesh)

    # Position the camera so it looks at the voxel centred at (0.5, 0.5, 0.5).
    camera = Camera(
        position=(4.0, 4.0, 4.0),
        yaw=-135.0,
        pitch=-30.0,
        fov=60.0,
        near=0.1,
        far=100.0,
    )

    clock        = pygame.time.Clock()
    mouse_captured = False
    frame        = 0
    orbit_speed  = 1.0   # degrees per frame
    zoom_speed   = 0.05  # world units per frame
    spd          = orbit_speed + zoom_speed

    print("Controls: W/S=zoom, A/D=orbit, Q/E=tilt, Esc=quit")

    running = True
    while running:
        clock.tick(60)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                running = False
            elif event.type == pygame.VIDEORESIZE:
                renderer.width  = event.w
                renderer.height = event.h

            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    if mouse_captured:
                        pygame.event.set_grab(False)
                        pygame.mouse.set_visible(True)
                        mouse_captured = False
                    else:
                        running = False
            elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                pygame.event.set_grab(True)
                pygame.mouse.set_visible(False)
                mouse_captured = True
            elif event.type == pygame.VIDEORESIZE:
                renderer.width  = event.w
                renderer.height = event.h

        if mouse_captured:
            dx, dy = pygame.mouse.get_rel()
            camera.rotate(dx * orbit_speed, -dy * orbit_speed)
        else:
            pygame.mouse.get_rel()  # consume to avoid jumps

        keys = pygame.key.get_pressed()
        if keys[pygame.K_w]:      camera.move_forward( spd)
        if keys[pygame.K_s]:      camera.move_forward(-spd)
        if keys[pygame.K_a]:      camera.move_right(  -spd)
        if keys[pygame.K_d]:      camera.move_right(   spd)
        if keys[pygame.K_q]:      camera.move_up(     -spd)
        if keys[pygame.K_e]:      camera.move_up(      spd)

        renderer.render(camera)
        renderer.swap()

        frame += 1
        if max_frames > 0 and frame >= max_frames:
            break

    renderer.cleanup()


# ── Headless / CI mode ─────────────────────────────────────────────────────────

def run_headless(mesh: list) -> None:
    """Verify mesh upload via the null renderer (no display required)."""
    renderer = VoxelRenderer(headless=True)
    renderer.upload_chunk_mesh(0, 0, 0, mesh)
    camera = Camera(position=(4.0, 4.0, 4.0), yaw=-135.0, pitch=-30.0)
    renderer.render(camera)
    renderer.swap()
    renderer.cleanup()
    print(f"Headless render complete — mesh has {len(mesh) // 7} vertices.")


# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    args       = parse_args()
    biome_type = BIOME_MAP[args.biome]

    # Generate the single voxel using the C++ engine.
    chunk = make_single_voxel_chunk(biome_type)
    print_voxel_info(chunk, args.biome)

    mesh = chunk.build_mesh()
    if not mesh:
        print("WARNING: Mesh is empty – no visible faces generated.")
        return

    headless = args.headless or not _HAS_OPENGL or not _HAS_PYGAME
    if headless:
        run_headless(mesh)
    else:
        run_interactive(mesh, args.biome, args.frames)


if __name__ == "__main__":
    main()
